"""
Execute generated evaluators on programs via subprocess isolation.

Uses the same subprocess + pickle pattern as the existing evaluator.py
but adapted for arbitrary evaluator code generated by the LLM.
"""

import os
import pickle
import subprocess
import sys
import tempfile
from typing import Dict, Optional, Set

from .config import OuterLoopConfig
from .strategy import NoiseResult


class EvaluatorRunner:
    """Runs a generated evaluator on programs in isolated subprocesses."""

    def __init__(self, config: OuterLoopConfig):
        self.config = config
        self.base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        self.project_root = os.path.join(self.base_dir, "deps", "Index_EAB")
        self.last_corpus_errors: Set[str] = set()

    def evaluate_program(
        self,
        evaluator_code: str,
        program_path: str,
        timeout: Optional[int] = None,
    ) -> Dict[str, float]:
        """Run a generated evaluator on a single program.

        Args:
            evaluator_code: The complete evaluator .py file content.
            program_path: Path to the program to evaluate.
            timeout: Override default timeout.

        Returns:
            Dictionary with evaluation metrics (must include 'combined_score').
        """
        timeout = timeout or self.config.eval_timeout

        # Write the evaluator code to a temp file
        eval_fd, eval_path = tempfile.mkstemp(suffix="_evaluator.py", prefix="outer_")
        # Write the runner script
        runner_fd, runner_path = tempfile.mkstemp(suffix="_runner.py", prefix="outer_")
        results_path = runner_path + ".results"

        try:
            with os.fdopen(eval_fd, "w") as f:
                f.write(evaluator_code)

            runner_script = f"""
import sys
import os
import pickle
import traceback

# Set up environment
os.environ['BENCHMARK'] = '{self.config.benchmark}'
os.chdir('{self.project_root}')
sys.path.insert(0, '{self.project_root}')
sys.path.insert(0, '{self.base_dir}')

try:
    # Import the generated evaluator
    import importlib.util
    spec = importlib.util.spec_from_file_location("gen_evaluator", '{eval_path}')
    evaluator = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(evaluator)

    # Call evaluate()
    result = evaluator.evaluate('{program_path}')

    if not isinstance(result, dict):
        raise TypeError(f"evaluate() must return dict, got {{type(result)}}")
    if 'combined_score' not in result:
        raise KeyError("evaluate() result must include 'combined_score'")

    with open('{results_path}', 'wb') as f:
        pickle.dump({{'result': result}}, f)

except Exception as e:
    traceback.print_exc()
    with open('{results_path}', 'wb') as f:
        pickle.dump({{'error': str(e), 'traceback': traceback.format_exc()}}, f)
"""
            with os.fdopen(runner_fd, "w") as f:
                f.write(runner_script)

            # Run in subprocess
            process = subprocess.Popen(
                [sys.executable, runner_path],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )

            try:
                stdout, stderr = process.communicate(timeout=timeout)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait()
                return {
                    "combined_score": 0.0,
                    "error": f"Evaluation timed out after {timeout}s",
                }

            if process.returncode != 0:
                stderr_text = stderr.decode()[-500:] if stderr else ""
                return {
                    "combined_score": 0.0,
                    "error": f"Process exited with code {process.returncode}: {stderr_text}",
                }

            # Load results
            if not os.path.exists(results_path):
                return {
                    "combined_score": 0.0,
                    "error": "Results file not created",
                }

            with open(results_path, "rb") as f:
                data = pickle.load(f)

            if "error" in data:
                return {
                    "combined_score": 0.0,
                    "error": data["error"],
                    "traceback": data.get("traceback", ""),
                }

            return data["result"]

        finally:
            for path in [eval_path, runner_path, results_path]:
                if os.path.exists(path):
                    try:
                        os.unlink(path)
                    except OSError:
                        pass

    def evaluate_corpus(
        self,
        evaluator_code: str,
        corpus,
    ) -> Dict[str, float]:
        """Evaluate all programs in the corpus with a generated evaluator.

        Args:
            evaluator_code: The complete evaluator .py file content.
            corpus: ProgramCorpus instance.

        Returns:
            Dict mapping program name → combined_score.
            Programs that error out get score 0.0.
            Sets self.last_corpus_errors with names of programs that errored.
        """
        scores = {}
        self.last_corpus_errors = set()
        for program in corpus.programs:
            print(f"  Evaluating {program.name}...", end=" ", flush=True)
            result = self.evaluate_program(evaluator_code, program.path)
            score = result.get("combined_score", 0.0)
            scores[program.name] = score

            if "error" in result:
                print(f"ERROR: {result['error'][:80]}")
                self.last_corpus_errors.add(program.name)
            else:
                print(f"score={score:.4f}")

        return scores

    def measure_noise(
        self,
        evaluator_code: str,
        program_path: str,
        num_runs: Optional[int] = None,
    ) -> NoiseResult:
        """Measure evaluator noise by running it multiple times on the same program.

        Args:
            evaluator_code: The complete evaluator .py file content.
            program_path: Path to the program to evaluate repeatedly.
            num_runs: Number of repeated evaluations.

        Returns:
            NoiseResult with statistics.
        """
        num_runs = num_runs or self.config.noise_check_runs
        scores = []

        for i in range(num_runs):
            result = self.evaluate_program(evaluator_code, program_path)
            if "error" not in result:
                scores.append(result["combined_score"])

        return NoiseResult(scores=scores)
